### PR TITLE
Under 50k fix

### PR DESCRIPTION
**Pull request by cjbt**
After: 
Screen Shot 2019-03-23 at 10 38 02 PM

### CODE REVIEW

**Comment by cjbt** [comment]
Btw, I enjoyed reading through the codebase. Clean code. I took some notes on readability and how declarative everthing was. 👍

**Comment by cjbt** [comment]
Hmm my prettier settings changed all the double quotes to single. I'm going to turn that off before I drive anyone nuts every time I try to contribute.

**Comment by tommaay** [comment]
@cjbt Haha thanks man the code is still pretty messy we were all pretty noobie when we made this app. I wanted to clean up and refactor the code but I've been too busy with other projects

**Comment by cjbt** [comment]
@tommaay np, A lot more could be done ie: if starting salary was under 50k, but annualRaise bumped it up to 50k. 

I noticed the twitter stuff and honestly you guys built a great app. Kudos! Hopefully I get to contribute more.

**Comment by tommaay** [comment]
@cjbt Thanks if you have anymore feedback or wanna pair program to add some more functionality let me know!

**Comment by cjbt** [comment]
Honestly would have done the same thing haha. 💯

**Pull request merged**
